# Generated by Django 2.1.2 on 2018-10-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date_of_registration', models.DateField(blank=True)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('dod', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedigree.Breeder')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pedigree.Breeder')),
                ('parent_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farther', to='pedigree.Pedigree')),
                ('parent_mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='pedigree.Pedigree')),
            ],
        ),
        migrations.RemoveField(
            model_name='goat',
            name='breeder',
        ),
        migrations.RemoveField(
            model_name='goat',
            name='current_owner',
        ),
        migrations.DeleteModel(
            name='Goat',
        ),
    ]
