# Generated by Django 2.1.2 on 2018-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_auto_20181015_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dod',
            field=models.DateField(blank=True),
        ),
    ]
