# Generated by Django 2.1.2 on 2019-01-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0006_auto_20181015_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedigreeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedigree',
            name='image',
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedigree.Breeder'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pedigree.Breeder'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='pedigreeimages',
            name='reg_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pedigree.Pedigree'),
        ),
    ]
