# Generated by Django 2.1.2 on 2019-01-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0007_auto_20190120_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedigreeImages',
            new_name='PedigreeImage',
        ),
    ]
