# Generated by Django 2.1.2 on 2019-01-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0008_auto_20190120_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigreeimage',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedigreeimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
