# Generated by Django 2.1.2 on 2019-01-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0009_auto_20190120_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
