# Generated by Django 2.1.2 on 2019-01-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0010_pedigree_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedigreeAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs_per_week', models.IntegerField(default=0)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='pedigree.Pedigree')),
            ],
        ),
    ]
