# Generated by Django 2.1.2 on 2019-01-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0011_pedigreeattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='pedigree.Pedigree'),
        ),
    ]
