# Generated by Django 2.1.2 on 2019-01-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0014_auto_20190125_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='reg_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attribute', serialize=False, to='pedigree.Pedigree'),
        ),
    ]
