# Generated by Django 2.1.2 on 2019-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0015_auto_20190125_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigreeattributes',
            name='prize_winning',
            field=models.BooleanField(default=False),
        ),
    ]
