# Generated by Django 2.1.2 on 2019-01-27 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0016_pedigreeattributes_prize_winning'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedigree',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 27, 20, 31, 42, 135475, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
