# Generated by Django 2.1.2 on 2019-01-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0017_pedigree_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='pedigree.Breeder'),
        ),
    ]
