# Generated by Django 2.1.2 on 2019-01-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0019_auto_20190128_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedigree',
            name='breed',
        ),
        migrations.AddField(
            model_name='pedigreeattributes',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='pedigree.Breed'),
        ),
    ]
