# Generated by Django 2.1.2 on 2019-01-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0021_auto_20190129_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
