# Generated by Django 2.1.2 on 2019-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0022_auto_20190129_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10, null=True),
        ),
    ]
