# Generated by Django 2.1.2 on 2019-01-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0023_auto_20190129_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='date_of_registration',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dob',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dod',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
