# Generated by Django 2.1.2 on 2019-01-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0024_auto_20190129_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigreeattributes',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='breed.Breed'),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
