# Generated by Django 2.1.2 on 2019-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0025_auto_20190130_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedigree',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
