# Generated by Django 2.1.2 on 2019-02-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0027_auto_20190201_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedigree',
            old_name='notes',
            new_name='note',
        ),
    ]
